### ISSUE TITLE
Possibility to sort the columns

### ISSUE THREAD

**Issue by paarals** [openpoke/decidim-module-anonymous_codes#18]
![imatge](https://github.com/openpoke/decidim-module-anonymous_codes/assets/40388743/3e39e532-3625-4ec3-bb8b-aac622944283)

If you click on the name, it is organised alphabetically (as proposals)
![imatge](https://github.com/openpoke/decidim-module-anonymous_codes/assets/40388743/224ca806-10ad-4522-94b5-6ca5a4c0c250)

**Comment by microstudi** [comment]
Done by #19
