### ISSUE TITLE
Improvements & feedback

### ISSUE THREAD

**Issue by microstudi** [openpoke/decidim-module-anonymous_codes#20]
- [x] On a survey component's admin page, there is a link “Create answer codes here”: The should open in a new tab `target="_blank"`
- [x] In the same page, also open in a new tab if there's a code applied that takes you to the survey
- [x] Add a link to administrate the component survey from the anonymous codes groups page
- [x] Allow admins to introduce manual codes instead of automatics

**Comment by paarals** [comment]
closeda via #21
